; Local Development Configuration

; Specifies the path and name of the SQLite database file.
; SQLite creates a database file directly on the filesystem.
; Example Value: db_name = /path/to/registry_database.db
[database]
db_name = ./database/registry_database.db
